name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install build dependencies
      run: |
          sudo apt update
          sudo apt install debhelper dpkg-dev autotools-dev gtk-doc-tools \
              intltool libdbus-glib-1-dev  libglib2.0-dev libgtk-3-dev \
              libexif-dev libmenu-cache-dev libtool pkg-config valac \
              libglib2.0-doc libgtk-3-doc libgtk-layer-shell-dev -y
    - name: configure
      run: |
          autoreconf -fvi
          ./configure \
              --enable-debug \
              --enable-wayland \
              --enable-x11
    - name: make
      run: make
    - name: check
      run: make check
    - name: install
      run: sudo make install
